version: 2
jobs:
  # build:    
  #   working_directory: /home/node
  #   docker:
  #     - image: node:9.8.0
  #   steps:
  #     - checkout
  deploy_qa:
    cache_directories:
      - /home/node/
    working_directory: /home/node
    docker:
      - image: node:9.8.0
        command: bash
        user: node        
    steps:
      - checkout
      - run:
          name: Extracting GCP Service key
          command: |
            echo $QA_GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > $CIRCLE_WORKING_DIRECTORY/etc/gcloud-service-key.json
      - run:
          name: Installing NebulaE-cli
          command: |
            npm config set prefix '~/.npm-global'
            export PATH=~/.npm-global/bin:$PATH
            source ~/.profile
            npm install -g nebulae            
      - run:
          name: Registering Micro-FrontEnd
          command: |
            nebulae register microfrontend --microservice-id=$CIRCLE_PR_REPONAME --frontend-id=emi --file=$CIRCLE_WORKING_DIRECTORY/etc/mfe-setup.json --store-type=GCP_DATASTORE --gcp-service-account-token=$CIRCLE_WORKING_DIRECTORY/etc/gcloud-service-key.json
      #- run:
       #   name: Deploy on Kubernetes
        #  command: |
         #   kubectl apply -f /home/node
workflows:
  version: 2
  build-and-deploy:
    jobs:
      # - build:
      #     context: lab-microservices
      - deploy_qa:
          context: lab-microservices
          # requires:
          #   - build